services:
  - type: web
    name: contextbot
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false